### ISSUE TITLE
我持续关注，看看你水平能有多高~~~

### ISSUE THREAD

**Issue by ParryQiu** [DanceSmile/DanceSmile.github.io#19]
我非常感兴趣你哪里来的自信直接说别人开发的项目「太丑了」的？
我来看看你做过的项目！！！

**Comment by DanceSmile** [comment]
整个事件的过程
https://www.v2ex.com/t/484833#reply50

**Comment by ParryQiu** [comment]
![](https://oindk07nf.qnssl.com/Jietu20180904-230850@2x.png)

你这个人为什么两面派？为什么又对我们的学员自己写出来的学习项目上来就评价出「太丑了」呢？
「不要随便践踏别人的尊严 学习技术写的项目不容易」，元气满满呢~~~
别写一堆了，一句都没看，多花点时间上传点你的项目吧！！！

**Comment by ParryQiu** [comment]
还有你为什么去 v2ex 发帖呢？你可以随口评价别人学习的项目「太丑了」，我作为群主骂你你就受不了了？到处发帖觉得自己冤枉了？玻璃心了？觉得被侵犯了？觉得委屈？觉得不被我尊重了？

还有啊，你为什么在百度贴吧发那么多的帖子？还用贴吧小号发那么多色情贴？
是不是很喜欢发帖子？请你告诉我？！
不告诉我，我就去你的 v2ex 帖子下去问问你。
